import Head from 'next/head'
import { useState } from 'react';
import styles from '../styles/Home.module.scss'
import LeftSide from './components/LeftSide'
import RightSide from './components/RightSide';
// import SideBar from './components/SideBar';
import { AwesomeButton, AwesomeButtonProgress} from "react-awesome-button";
import 'react-awesome-button/dist/styles.css';
import 'react-awesome-button/dist/themes/theme-bruce.css';
import axios from 'axios';
import { BugIcon } from "@primer/octicons-react"; // custom icons
export default function Home() {
  const [inputCode, setInputCode] = useState("");
  const [outputCode, setOutputCode] = useState("");
  const [respondData, setRespondData] = useState([]);

  const handleClick = (next) => {
    // axios.post('https://bc3e-27-2-12-103.ap.ngrok.io/predict', {inputCode})
    axios.post('http://localhost:5000/predict', {inputCode})
      .then((res) => {
        setOutputCode(inputCode);
        setRespondData(res);
        next()
      })
      .catch(err => console.error(err))
  };

  return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div className='body-container'>
            <div className='code-container'>
              <div className='in-out-container'>
                <LeftSide inputCode={inputCode} setInputCode={setInputCode} />
                <RightSide outputCode={outputCode} data={respondData} />
              </div>
              <AwesomeButtonProgress 
                
                type="github" 
                onPress={async (element, next)=>{
                  console.log('got here')
                  handleClick(next)
                }}
                style={{
                  width: '200px',
                  height: '70px',
                }}
                size='icon'
              >
                <BugIcon/> Detect 
              </AwesomeButtonProgress>
            </div>
          </div>
        </main>

      </div>
  )
}
